version: '3.8'

services:
  status-app:
    image: smileysv/status-app-srv:latest
    container_name: status-app-srv
    restart: always
    ports:
      - "8088:8000"
    volumes:
      - /opt/sas/data.json:/app/data.json
    environment:
      - PYTHONUNBUFFERED=1